target 'MRGPagerController', :exclusive => true do
  pod "MRGPagerController", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "MRGPagerController", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
