source 'https://github.com/CocoaPods/Specs.git'

target 'MRGPagerController_Example', :exclusive => true do
  pod "MRGPagerController", :path => "../"
end

target 'MRGPagerController_Tests', :exclusive => true do
  pod "MRGPagerController", :path => "../"

  
end
